name: Generate Docs Preview

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout tbdocs repository
      uses: actions/checkout@v3
    
    - name: Build the tbdoc Docker image
      run: docker build -t tbdoc:1.0.0 tbdoc

    - name: print out directory contents
      run: ls -al
