name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout tbdocs repository
      uses: actions/checkout@v3
    
    - name: Build the tbdoc Docker image
      run: docker build -t tbdoc:1.0.0 tbdoc
