name: Generate Docs Preview

on:

  workflow_dispatch:
  push:
    branches: [ "main", "feat/github-actions"]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout tbdocs repository
      uses: actions/checkout@v3
    
    - name: Build the tbdoc Docker image
      run: docker build -t tbdoc:1.0.0 tbdoc

    - name: generate markdown files
      run: docker run --rm -v "$PWD/topics":/app/topics -v "$PWD/build":/app/build tbdoc:1.0.0

    - name: print out directory contents
      run: tree build/
